# Generated by Django 5.1.1 on 2026-02-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_ingredientinrecipe_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_hash',
            field=models.CharField(blank=True, help_text='Уникальный короткий идентификатор для ссылки', max_length=8, null=True, unique=True, verbose_name='Короткий хэш'),
        ),
    ]
