# Generated by Django 5.1.1 on 2026-02-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_follow_options_follow_unique_follow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='short_hash',
        ),
        migrations.AddField(
            model_name='recipe',
            name='short_code',
            field=models.CharField(blank=True, help_text='Уникальный короткий код для ссылки', max_length=8, null=True, unique=True, verbose_name='Короткий код'),
        ),
    ]
